name: Test-build Kernel

on: [ push ]

jobs:
  build:
    name: ${{ matrix.target_arch }}
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        target_arch: [ amd64, aarch64 ]
        include:
          - target_arch: amd64
            target: amd64
          - target_arch: aarch64
            target: arm64
    steps:
      - uses: actions/checkout@v3
      - name: Build
        id: Build
        uses: vmactions/freebsd-vm@v0
        with:
          run: |
            wd
            ls -lah
            whoami
            env
            freebsd-version
