name: Test-build Kernel

on: [ push ]

jobs:
  build:
    name: ${{ matrix.target_arch }}
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        target_arch: [ amd64, aarch64 ]
        include:
          - target_arch: amd64
            target: amd64
          - target_arch: aarch64
            target: arm64
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: cross-platform-actions/action@v0.15.0
        with:
          operating_system: freebsd
          version: '13.2'
          shell: bash
          run: |
            pwd
            ls -lah
            whoami
            env
            freebsd-version
            sudo pkg install -y llvm16 git-lite
            mkdir -p ${HOME}/obj
            env MAKEOBJDIRPREFIX=${HOME}/obj make -j$(sysctl -n hw.ncpu) CROSS_TOOLCHAIN=llvm16 WITHOUT_TOOLCHAIN=yes buildkernel TARGET_ARCH=${{ matrix.target_arch }}
